#!/bin/bash
#
# Put contents of file $1, version $2, into data repository.

file=$1
version=$2

versions_repo=`pwd`
dow_root=$(dirname "$versions_repo")
data_repo=$(dirname "$dow_root")
mock_repo=$dow_root/mock_repo

if ! [ -e "$mock_repo/$file/$version" ]; then
  echo "Version $version of $file not available."
  exit 1
fi

mkdir -p "$data_repo/$(dirname $file)"
cp "$mock_repo/$file/$version" "$data_repo/$file"

