#!/bin/bash
#
# To be called from data repository.
#
# Synchronize current branch with CVS.

data_repo=`pwd`
dow_root=$data_repo/.dow
versions_repo=$dow_root/versions
map=$dow_root/map
utils=$dow_root/utils
cvs_cmd=$dow_root/cvs_cmd

if ! $utils/check_clean_status; then
  echo "Repository $(pwd) status not clean."
  exit 1
fi

head=`cat .git/HEAD`

if [ "${head:0:21}" = 'ref: refs/heads/sync/' ]; then
  echo "fatal: Attempting to synchronize a synchronization branch."
  exit 1
fi

if [ "${head:0:16}" != 'ref: refs/heads/' ]; then
  echo 'fatal: Detached HEAD.'
  exit 1
fi

branch=${head:16}

if base=^$(git rev-parse --quiet --verify sync/"$branch"); then
  if ! git merge-base --is-ancestor sync/"$branch" "$branch"; then
    echo "Error: Non fast-forward."
    exit 1
  fi
elif mapped_base=$(git -C "$versions_repo" rev-parse --quiet --verify "$branch"); then
  base=$("$utils"/map_lookup "$map" $mapped_base) &&
  git branch sync/"$branch" $base
  if [ $? -ne 0 ]; then
    exit 1
  fi
  base=^$base
else
  base= #empty
fi

while read commit parent merge_parents; do
  if [ -z "$commit" ]; then
    echo "Already up-to-date."
    exit 0
  fi

  if [ -n "$parent" ]; then
    against=$parent
  else
    # Initial commit: diff against an empty tree object.
    against=4b825dc642cb6eb9a060e54bf8d69288fbee4904
  fi

  delete=`git diff --diff-filter=D --name-only $against $commit`
  add=`git diff --diff-filter=A --name-only $against $commit`
  modify=`git diff --diff-filter=M --name-only $against $commit`
  message=`git log -1 --format=format:%B $commit`

  git checkout $commit

  cd $versions_repo

  if ! $utils/git_checkout_put "$map" detail/"$branch" $parent $merge_parents; then
    exit 1
  fi

  if [ -z "$delete$add$modify" ]; then
    # Empty commit. Nothing to do here.
    exit 0
  fi

  # TODO: Take other parents into account.
  #       For now, we require that the files in the main parent are synchronized
  #       or not modified.

  # Begin: Locks and checks
  version_array=( `$cvs_cmd/lock $delete $add $modify` )
  if ! [ $? -eq 0 ]; then
    $cvs_cmd/unlock $delete $add $modify
    exit 1
  fi

  delete_array=( $delete )
  add_array=( $add )
  modify_array=( $modify )

  if ! [ ${#version_array[@]} -eq $(( ${#delete_array[@]} + ${#add_array[@]} + ${#modify_array[@]} )) ]; then
    echo "Oops. Array sizes mismatch: ${#version_array[@]} != ${#delete_array[@]} + ${#add_array[@]} + ${#modify_array[@]}"
    $cvs_cmd/unlock $delete $add $modify
    exit 1
  fi

  i=0
  d=${#delete_array[@]}
  a=$((d + ${#add_array[@]}))
  m=$((a + ${#modify_array[@]}))
  mismatch=0
  for (( ; i < d; ++i)); do # Removes
    expected="A`git show HEAD:${delete_array[i]}`"
    if ! [ ${version_array[i]} == $expected ]; then
      echo "Version mismatch: $expected < ${version_array[i]} ${delete_array[i]}"
      mismatch=1
    fi
  done
  for (( ; i < a; ++i)); do # Adds
    # TODO: Consider file ressurrection.
    expected="A1.0"
    if ! [ ${version_array[i]} == $expected ]; then
      echo "Version mismatch: $expected < ${version_array[i]} ${add_array[$((i-d))]}"
      mismatch=1
    fi
  done
  for (( ; i < m; ++i)); do # Modifies
    expected="A`git show HEAD:${modify_array[$((i-a))]}`"
    if ! [ ${version_array[i]} == $expected ]; then
      echo "Version mismatch: $expected < ${version_array[i]} ${modify_array[$((i-a))]}"
      mismatch=1
    fi
  done

  if [ $mismatch -ne 0 ]; then
    $cvs_cmd/unlock $delete $add $modify
    exit 1;
  fi
  # End: Locks and checks

  # Apply removes.
  if [ -n "$delete" ]; then
    cd "$data_repo"
    $cvs_cmd/rm "$message" $delete
    cd "$versions_repo"
    git rm $delete
  fi

  # Apply additions.
  for file in $add; do
    mkdir -p $(dirname $file)
    # TODO: Consider file ressurrection.
    echo 1.1 > $file
  done

  # Apply modifications.
  for file in $modify; do
    mkdir -p $(dirname $file)
    $utils/version_advance `git show :0:$file` 1 > $file
  done

  if [ -n "$add$modify" ]; then
    cd "$data_repo"
    $cvs_cmd/ci "$message" $add $modify
    cd "$versions_repo"
    git add $add $modify
  fi

  cd $data_repo

  touch "$dow_root"/modification_commit
  $utils/git_commit_to_other $versions_repo
done <<<"$(git rev-list --reverse --parents "$branch" $base)"

# Checkout.
if git rev-parse --quiet --verify sync/"$branch" > /dev/null; then
  git checkout sync/"$branch"
else
  git checkout --orphan sync/"$branch"
  git rm -rf . 2> /dev/null
fi

git merge "$branch"

cd $versions_repo

# Checkout.
if git rev-parse --quiet --verify $branch > /dev/null; then
  git checkout $branch
else
  git checkout --orphan $branch
  git rm -rf . 2> /dev/null
fi

git merge detail/$branch
git branch -d detail/$branch

