#!/bin/bash
#
# Initialize a mirrored repository.

vcs=$1
srcdir=`readlink -f "$2"`

git init
echo .dow >> .git/info/exclude
mkdir .dow

cd .dow
git init versions
mkdir map
mkdir ${vcs}_repo
ln -s "$srcdir" srcdir

ln -s srcdir/utils .
ln -s srcdir/${vcs}_cmd cvs_cmd

cd versions/.git/hooks
ln -s ../../../srcdir/hooks/versions/pre-commit .
ln -s ../../../srcdir/hooks/versions/commit-msg .
ln -s ../../../srcdir/hooks/versions/post-commit .

cd ../../../../.git/hooks
ln -s ../../.dow/srcdir/hooks/data/pre-commit .
ln -s ../../.dow/srcdir/hooks/data/post-commit .

