#!/bin/bash
#
# Generate CVS commits.
#
# First argument is the commit message. Following are the file paths to be
# updated.
#
# File contents are copied from the HEAD of the data repository. Files are
# unlocked after successful commits.

message=$1
shift

dow_root=$(dirname "$(pwd)")
data_repo="$dow_root/data"
cvs_repo="$dow_root/cvs_repo"
export CVSROOT=$(awk -F "=" '/^CVS.ROOTPATH[ =]/{gsub(/[ \t]*/,"",$2);print $2}' "$dow_root/config")

cd $data_repo

for file in "$@"; do
  git show HEAD:$file > $cvs_repo/$file
done

cd $cvs_repo
cvs add "$@"
#> /dev/null/ 2>&1
cvs commit -m "$message"
