#!/bin/bash
#
# Put contents of file $1, version $2, into data repository.

file=$1
version=$2

dow_root=$(dirname "$(pwd)")
data_repo="$dow_root/data"
cvs_repo="$dow_root/cvs_repo"
export CVSROOT=$(awk -F "=" '/^CVS.ROOTPATH[ =]/{gsub(/[ \t]*/,"",$2);print $2}' "$dow_root/config")

cd $cvs_repo

#enter module before update(fix strange cvs-update behaviour)
module=${file%%/*}
trail=${file#*/}
cd $module
cvs update -d ${trail%%/*}
cd -
cvs update -r $version $file
#> /dev/null/ 2>&1
if [ ! -f $file ]; then
  echo "Version $version of $file not available."
  exit 1
fi

mkdir -p "$data_repo/$(dirname $file)"
cp -f "$file" "$data_repo/$file"
