#!/bin/bash
#
# Output if successful: List of latest versions of locked files, in the order
# given in the input, with the following format:
#   A1.5 : File is alive, and current version is 1.5
#   D1.5 : File is dead, and last version was 1.5
#   A1.0 : No version of the file in the repository.

dow_root=$(dirname "$(pwd)")
cvs_repo="$dow_root/cvs_repo"
export CVSROOT=$(awk -F "=" '/^CVS.ROOTPATH[ =]/{gsub(/[ \t]*/,"",$2);print $2}' "$dow_root/config")

cd $cvs_repo
#cvs doesnt support lock natively, so this script also does not. Sorry
#but if it did , this would be the place.
for param in "$@"
do
  while read line
  do
    if [[ -z $line ]]; then
      echo A1.0
    else
      isdead=$(echo "$line" | cut -c 43-46)
      if [[  $isdead == 'dead' ]]; then
        echo D$(echo "$line" | cut -d ' ' -f5)
      else
        echo A$(echo "$line" | cut -d ' ' -f5)
      fi
    fi
  done <<<"$(cvs rls -d -l $param 2>/dev/null)"
done
exit
