#!/bin/bash
#
# Output if successful: List of latest versions of locked files, in the order
# given in the input, with the following format:
#   A1.5 : File is alive, and current version is 1.5
#   D1.5 : File is dead, and last version was 1.5
#   A1.0 : No version of the file in the repository.

dow_root=$(dirname "$(pwd)")
cvs_repo="$dow_root/cvs_repo"
export CVSROOT=$(awk -F "=" '/^CVS.ROOTPATH[ =]/{gsub(/[ \t]*/,"",$2);print $2}' "$dow_root/config")

cd $cvs_repo

#cvs doesnt support lock natively, so this script also does not. Sorry
#but if it did , this would be the place.
for param in "$@"
do
  if [[ ! -d $(dirname "$param") ]] ; then
    module=${param%%/*}
    trail=${param#*/}
    cd $module
    cvs update -CdA ${trail%%/*} 2> /dev/null
    cd -
  else
    cvs update -CdA $param 2> /dev/null
  fi
done

while (($#)); do
  out=$(cvs status $1)
  if echo "$out" | grep 'Status: Unknown' 2> /dev/null; then
    echo A1.0
  elif echo "$out" | grep 'Working revision:[[:space:]]\+[0-9]\+\(\.[0-9]\+\)*' > /dev/null; then
    echo "$out" | awk '/[ ]*Working revision:*/{print "A"$3}'
  else
    echo "$out" | awk '/[ ]*Repository revision:*/{print "D"$3}'
  fi
  shift
done
