#!/bin/bash
#
# Apply commit to data repository.

# Index and parents setup in pre-commit hook.

data_repo=../data
utils=../utils

if [ -e ../synchronization_commit ]; then
  rm ../synchronization_commit
  $utils/git_commit_to_other.sh $data_repo
fi

versions_sha=`git rev-parse HEAD`
cd $data_repo
data_sha=`git rev-parse HEAD`

$utils/map_store.sh $versions_sha $data_sha

