#!/bin/bash
#
# Checkout branch and setup parents in data repository. Assert coherency.

versions_repo=`pwd`
dow_root=$(dirname "$versions_repo")
data_repo=$(dirname "$dow_root")
map=$dow_root/map
utils=$dow_root/utils

versions_head_commit=`git rev-parse --quiet --verify HEAD`
versions_has_head=$? # 0 means yes.
head=`cat .git/HEAD`

if [ "${head:0:16}" != 'ref: refs/heads/' ]; then
  echo 'Detached HEAD. Aborting.'
  exit 1
fi

branch=${head:16}

cd $data_repo

if ! $utils/git_checkout "$map" "$branch" "$versions_repo" $versions_has_head $versions_head_commit; then
  exit 1
fi

