#!/bin/bash
#
# Update CVS-like repository and apply commit to versions repository.

versions_repo=../versions
utils=../utils
cvs_cmd=../cvs_cmd

# Skip if not a modification commit.
if ! [ -e ../modification_commit ]; then
  exit 0
fi

if git rev-parse --quiet --verify HEAD^ > /dev/null; then
  against=HEAD^
else
  # Initial commit: diff against an empty tree object.
  against=4b825dc642cb6eb9a060e54bf8d69288fbee4904
fi

delete=`git diff --diff-filter=D --name-only $against HEAD`
add=`git diff --diff-filter=AM --name-only $against HEAD`
message=`git log -1 --format=format:%B HEAD`

# Apply removes.
if [ -n "$delete" ]; then
  $cvs_cmd/rm "$message" $delete
fi

# Apply additions and modifications.
if [ -n "$add" ]; then
  $cvs_cmd/ci "$message" $add
fi

# TODO: Rollback and abort in case of CVS failure (unexpected).

$utils/git_commit_to_other $versions_repo
# Commit in versions repository updates database and removes
# ../modification_commit.

