#!/bin/bash
#
# Forbid commits on synchronization branches

head=`cat .git/HEAD`
if [ "${head:0:21}" = 'ref: refs/heads/sync/' ]; then
  echo 'fatal: Cannot commit on a synchronization branch.'
  echo "Commit on ${head:21} and then call dow-put."
  exit 1
fi

