#!/bin/bash
#
# Call appropriate form of merge with no rename detection.
#
# Newer versions support the no-renames option to the recursive strategy. For
# older versions, we fallback to the resolve strategy, which is more limited and
# ignores custom merge drivers.

utils=$(dirname "$BASH_SOURCE")
min_version=2.8.0.rc0
version=`git --version | cut -f3 -d ' '`
cmp=`$utils/compare_git_version "$version" "$min_version"`

if [ $? -eq 0 ] && [ "$cmp" -ge 0 ]; then
  git merge -X no-renames "$@"
else
  git merge --strategy=resolve "$@"
fi

