#!/bin/bash
#
# Attempt to modify outdated file should fail

. lib/init

cd "$DATA_REPO" &&
mkdir p &&
echo old > p/x &&
git add p/x &&
git commit -m old &&
git branch old &&
echo new > p/x &&
git add p/x &&
git commit -m new &&
"$SRCDIR"/dow-put &&
git checkout old &&
parent_data=$(git rev-parse old) &&
parent_versions=$("$UTILS"/map_lookup "$MAP" $parent_data) &&
git -C "$VERSIONS_REPO" branch old $parent_versions &&
# Attempt modification
echo override > p/x &&
git add p/x &&
git commit -m override &&
! "$SRCDIR"/dow-put &&
synced_data=$(git rev-parse sync/old) &&
synced_versions=$(git -C "$VERSIONS_REPO" rev-parse old) &&
test "$parent_data" = "$synced_data" &&
test "$parent_versions" = "$synced_versions" &&
git checkout -B old sync/old &&
# Attempt remove
git rm -f p/x &&
git commit -m remove &&
! "$SRCDIR"/dow-put &&
synced_data=$(git rev-parse sync/old) &&
synced_versions=$(git -C "$VERSIONS_REPO" rev-parse old) &&
test "$parent_data" = "$synced_data" &&
test "$parent_versions" = "$synced_versions" &&
# File was not deleted or modified
cd "$VERSIONS_REPO" &&
vcs_version=$("$CVS_CMD"/lock p/x) &&
test "$vcs_version" = A1.2

cleanup_test

